"""Auth subpackage for the Python port of Rust ``codex-login::auth``."""

from __future__ import annotations

from . import default_client
from .agent_identity import (
    AgentIdentityAuth,
    AgentIdentityAuthRecord,
    AgentIdentityKey,
    AgentTaskRegistrar,
    CODEX_AGENT_IDENTITY_AUTHAPI_BASE_URL_ENV_VAR,
    PROD_AGENT_IDENTITY_AUTHAPI_BASE_URL,
    agent_identity_authapi_base_url,
)
from .error import RefreshTokenFailedError, RefreshTokenFailedReason
from .external_bearer import (
    BearerTokenRefresher,
    ExternalAuthRefreshContext,
    ExternalAuthTokens,
    resolve_provider_auth_program,
    run_provider_auth_command,
)
from .manager import (
    AUTH_MODE_AGENT_IDENTITY,
    AUTH_MODE_API_KEY,
    AUTH_MODE_CHATGPT,
    AUTH_MODE_CHATGPT_AUTH_TOKENS,
    CLIENT_ID,
    CODEX_ACCESS_TOKEN_ENV_VAR,
    DEFAULT_CHATGPT_BACKEND_BASE_URL,
    EXTERNAL_AUTH_MODE_API_KEY,
    REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR,
    REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR,
    ApiKeyAuth,
    AuthConfig,
    AuthManager,
    AuthManagerConfig,
    ChatgptAuth,
    ChatgptAuthTokens,
    CodexAuth,
    ExternalAuth,
    ExternalAuthChatgptMetadata,
    ExternalAuthRefreshReason,
    ManagerExternalAuthTokens,
    RefreshTokenError,
    UnauthorizedRecovery,
    UnauthorizedRecoveryStepResult,
    auth_dot_json_from_external_access_token,
    auth_dot_json_from_external_tokens,
    classify_refresh_token_failure,
    enforce_login_restrictions,
    extract_refresh_token_error_code,
    load_auth,
    load_auth_dot_json,
    login_with_access_token,
    login_with_api_key,
    login_with_chatgpt_auth_tokens,
    logout,
    logout_all_stores,
    logout_with_revoke,
    persist_tokens,
    read_codex_access_token_from_env,
    read_codex_api_key_from_env,
    read_openai_api_key_from_env,
    refresh_token_endpoint,
    resolved_mode,
    save_auth,
    storage_mode,
)
from .revoke import revoke_auth_tokens, should_revoke_auth_tokens
from .storage import (
    AuthDotJson,
    AuthStorageBackend,
    AutoAuthStorage,
    EphemeralAuthStorage,
    FileAuthStorage,
    KeyringAuthStorage,
    create_auth_storage,
    delete_file_if_exists,
    get_auth_file,
)
from .util import try_parse_error_message


__all__ = [
    "AgentIdentityAuth",
    "AgentIdentityAuthRecord",
    "AgentIdentityKey",
    "AgentTaskRegistrar",
    "default_client",
    "CODEX_AGENT_IDENTITY_AUTHAPI_BASE_URL_ENV_VAR",
    "PROD_AGENT_IDENTITY_AUTHAPI_BASE_URL",
    "agent_identity_authapi_base_url",
    "RefreshTokenFailedError",
    "RefreshTokenFailedReason",
    "AUTH_MODE_AGENT_IDENTITY",
    "AUTH_MODE_API_KEY",
    "AUTH_MODE_CHATGPT",
    "AUTH_MODE_CHATGPT_AUTH_TOKENS",
    "CLIENT_ID",
    "CODEX_ACCESS_TOKEN_ENV_VAR",
    "DEFAULT_CHATGPT_BACKEND_BASE_URL",
    "EXTERNAL_AUTH_MODE_API_KEY",
    "REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR",
    "REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR",
    "ApiKeyAuth",
    "AuthConfig",
    "AuthManager",
    "AuthManagerConfig",
    "ChatgptAuth",
    "ChatgptAuthTokens",
    "CodexAuth",
    "ExternalAuth",
    "ExternalAuthChatgptMetadata",
    "ExternalAuthRefreshReason",
    "ManagerExternalAuthTokens",
    "RefreshTokenError",
    "UnauthorizedRecovery",
    "UnauthorizedRecoveryStepResult",
    "BearerTokenRefresher",
    "ExternalAuthRefreshContext",
    "ExternalAuthTokens",
    "AuthDotJson",
    "AuthStorageBackend",
    "AutoAuthStorage",
    "EphemeralAuthStorage",
    "FileAuthStorage",
    "KeyringAuthStorage",
    "create_auth_storage",
    "delete_file_if_exists",
    "get_auth_file",
    "auth_dot_json_from_external_access_token",
    "auth_dot_json_from_external_tokens",
    "classify_refresh_token_failure",
    "enforce_login_restrictions",
    "extract_refresh_token_error_code",
    "load_auth",
    "load_auth_dot_json",
    "login_with_access_token",
    "login_with_api_key",
    "login_with_chatgpt_auth_tokens",
    "logout",
    "logout_all_stores",
    "logout_with_revoke",
    "persist_tokens",
    "read_codex_access_token_from_env",
    "read_codex_api_key_from_env",
    "read_openai_api_key_from_env",
    "refresh_token_endpoint",
    "resolve_provider_auth_program",
    "revoke_auth_tokens",
    "run_provider_auth_command",
    "resolved_mode",
    "save_auth",
    "should_revoke_auth_tokens",
    "storage_mode",
    "try_parse_error_message",
]
