"""Python port entry point for Codex sandboxing.

Upstream Rust implementation for permissions and sandbox behavior lives in
``codex-rs/sandboxing``.  The currently implemented Python surface lives in
``pycodex.core.tools.sandboxing`` and ``pycodex.protocol``; this module
re-exports the implemented pieces under the canonical top-level import path
``pycodex.sandboxing``.
"""

from __future__ import annotations

from pycodex.core.tools import sandboxing as tool_sandboxing
from pycodex.protocol import (
    AskForApproval,
    ExecPolicyAmendment,
    FileSystemSandboxKind,
    FileSystemSandboxPolicy,
    GranularApprovalConfig,
    NetworkPermissions,
    ReviewDecision,
    SandboxPermissions,
)

from pycodex.core.tools.sandboxing import (
    ApprovalStore,
    ExecApprovalRequirement,
    PermissionRequestPayload,
    SandboxOverride,
    default_exec_approval_requirement,
    managed_network_for_sandbox_permissions,
    sandbox_override_for_first_attempt,
    with_cached_approval,
)
from pycodex.sandboxing.manager import (
    MissingLinuxSandboxExecutable,
    SandboxCommand,
    SandboxExecRequest,
    SandboxManager,
    SandboxTransformError,
    SandboxTransformRequest,
    SandboxType,
    SandboxablePreference,
    SeatbeltCommandBuilderUnavailable,
    SeatbeltUnavailable,
    Wsl1UnsupportedForBubblewrap,
    compatibility_sandbox_policy_for_permission_profile,
    effective_file_system_sandbox_policy,
    effective_network_sandbox_policy,
    effective_permission_profile,
    ensure_linux_bubblewrap_is_supported,
    get_platform_sandbox,
)
from pycodex.sandboxing.landlock import (
    CODEX_LINUX_SANDBOX_ARG0,
    create_landlock_command_args,
    create_landlock_command_args_for_permission_profile,
    create_linux_sandbox_command_args,
    create_linux_sandbox_command_args_for_permission_profile,
    linux_sandbox_arg0,
)
from pycodex.sandboxing.bwrap import (
    MISSING_BWRAP_WARNING,
    SYSTEM_BWRAP_PROGRAM,
    USER_NAMESPACE_FAILURES,
    USER_NAMESPACE_WARNING,
    WSL1_BWRAP_WARNING,
    find_system_bwrap_in_path,
    find_system_bwrap_in_search_paths,
    is_user_namespace_failure,
    is_wsl1,
    proc_version_indicates_wsl1,
    should_warn_about_system_bwrap,
    system_bwrap_has_user_namespace_access,
    system_bwrap_warning,
    system_bwrap_warning_for_path,
)
from pycodex.sandboxing.seatbelt import (
    CreateSeatbeltCommandArgsParams,
    MACOS_PATH_TO_SEATBELT_EXECUTABLE,
    MACOS_RESTRICTED_READ_ONLY_PLATFORM_DEFAULTS,
    MACOS_SEATBELT_BASE_POLICY,
    MACOS_SEATBELT_NETWORK_POLICY,
    PROXY_URL_ENV_KEYS,
    ProxyPolicyInputs,
    SeatbeltAccessRoot,
    UnixDomainSocketPolicy,
    UnixSocketPathParam,
    build_seatbelt_access_policy,
    build_seatbelt_unreadable_glob_policy,
    canonicalize_glob_static_prefix_for_sandbox,
    create_seatbelt_command_args,
    create_seatbelt_command_args_for_legacy_policy,
    dynamic_network_policy,
    dynamic_network_policy_for_network,
    has_proxy_url_env_vars,
    is_loopback_host,
    protected_metadata_names_for_writable_root,
    proxy_loopback_ports_from_env,
    proxy_policy_inputs,
    proxy_scheme_default_port,
    proxy_url_env_value,
    seatbelt_protected_metadata_name_regex,
    seatbelt_regex_for_unreadable_glob,
    unix_socket_dir_params,
    unix_socket_path_param_key,
    unix_socket_path_params,
    unix_socket_policy,
)
from pycodex.sandboxing.policy_transforms import (
    effective_file_system_sandbox_policy,
    effective_glob_scan_depth,
    effective_network_sandbox_policy,
    effective_permission_profile,
    intersect_permission_profiles,
    merge_file_system_policy_with_additional_permissions,
    merge_glob_scan_max_depth,
    merge_permission_profiles,
    normalize_additional_permissions,
    should_require_platform_sandbox,
)

__all__ = [
    "ApprovalStore",
    "CODEX_LINUX_SANDBOX_ARG0",
    "ExecApprovalRequirement",
    "MISSING_BWRAP_WARNING",
    "MissingLinuxSandboxExecutable",
    "PermissionRequestPayload",
    "SandboxCommand",
    "SandboxExecRequest",
    "SandboxManager",
    "SandboxOverride",
    "SandboxTransformError",
    "SandboxTransformRequest",
    "SandboxType",
    "SandboxablePreference",
    "SeatbeltCommandBuilderUnavailable",
    "SeatbeltUnavailable",
    "SYSTEM_BWRAP_PROGRAM",
    "ReviewDecision",
    "SandboxPermissions",
    "USER_NAMESPACE_FAILURES",
    "USER_NAMESPACE_WARNING",
    "WSL1_BWRAP_WARNING",
    "Wsl1UnsupportedForBubblewrap",
    "NetworkPermissions",
    "FileSystemSandboxKind",
    "FileSystemSandboxPolicy",
    "GranularApprovalConfig",
    "AskForApproval",
    "ExecPolicyAmendment",
    "compatibility_sandbox_policy_for_permission_profile",
    "create_landlock_command_args",
    "create_landlock_command_args_for_permission_profile",
    "create_linux_sandbox_command_args",
    "create_linux_sandbox_command_args_for_permission_profile",
    "default_exec_approval_requirement",
    "effective_file_system_sandbox_policy",
    "effective_glob_scan_depth",
    "effective_network_sandbox_policy",
    "effective_permission_profile",
    "ensure_linux_bubblewrap_is_supported",
    "find_system_bwrap_in_path",
    "find_system_bwrap_in_search_paths",
    "get_platform_sandbox",
    "intersect_permission_profiles",
    "is_user_namespace_failure",
    "is_wsl1",
    "linux_sandbox_arg0",
    "managed_network_for_sandbox_permissions",
    "merge_file_system_policy_with_additional_permissions",
    "merge_glob_scan_max_depth",
    "merge_permission_profiles",
    "normalize_additional_permissions",
    "proc_version_indicates_wsl1",
    "sandbox_override_for_first_attempt",
    "should_require_platform_sandbox",
    "should_warn_about_system_bwrap",
    "system_bwrap_has_user_namespace_access",
    "system_bwrap_warning",
    "system_bwrap_warning_for_path",
    "with_cached_approval",
    "CreateSeatbeltCommandArgsParams",
    "MACOS_PATH_TO_SEATBELT_EXECUTABLE",
    "MACOS_RESTRICTED_READ_ONLY_PLATFORM_DEFAULTS",
    "MACOS_SEATBELT_BASE_POLICY",
    "MACOS_SEATBELT_NETWORK_POLICY",
    "PROXY_URL_ENV_KEYS",
    "ProxyPolicyInputs",
    "SeatbeltAccessRoot",
    "UnixDomainSocketPolicy",
    "UnixSocketPathParam",
    "build_seatbelt_access_policy",
    "build_seatbelt_unreadable_glob_policy",
    "canonicalize_glob_static_prefix_for_sandbox",
    "create_seatbelt_command_args",
    "create_seatbelt_command_args_for_legacy_policy",
    "dynamic_network_policy",
    "dynamic_network_policy_for_network",
    "has_proxy_url_env_vars",
    "is_loopback_host",
    "protected_metadata_names_for_writable_root",
    "proxy_loopback_ports_from_env",
    "proxy_policy_inputs",
    "proxy_scheme_default_port",
    "proxy_url_env_value",
    "seatbelt_protected_metadata_name_regex",
    "seatbelt_regex_for_unreadable_glob",
    "unix_socket_dir_params",
    "unix_socket_path_param_key",
    "unix_socket_path_params",
    "unix_socket_policy",
    "tool_sandboxing",
]

