import pycodex.rollout_trace as rollout_trace


def test_crate_root_reexports_follow_lib_rs_public_surface():
    # Rust source: rollout-trace/src/lib.rs plus model/mod.rs `pub use`.
    # Contract: the Python package exposes the Rust crate-root public surface
    # through `__all__` without star-exporting reducer implementation helpers.
    expected = {
        "AgentOrigin",
        "AgentPath",
        "AgentResultTracePayload",
        "AgentThread",
        "AgentThreadId",
        "CodeCell",
        "CodeCellId",
        "CodeCellRuntimeStatus",
        "CodeCellTraceContext",
        "CodeModeRuntimeToolId",
        "CodexTurn",
        "CodexTurnId",
        "Compaction",
        "CompactionCheckpointTracePayload",
        "CompactionId",
        "CompactionRequest",
        "CompactionRequestId",
        "CompactionTraceAttempt",
        "CompactionTraceContext",
        "ConversationBody",
        "ConversationChannel",
        "ConversationItem",
        "ConversationItemId",
        "ConversationItemKind",
        "ConversationPart",
        "ConversationRole",
        "CorrelationId",
        "EdgeId",
        "ExecutionStatus",
        "ExecutionWindow",
        "InferenceCall",
        "InferenceCallId",
        "InferenceTraceAttempt",
        "InferenceTraceContext",
        "InteractionEdge",
        "InteractionEdgeKind",
        "McpCallId",
        "McpCallTraceContext",
        "ModelVisibleCallId",
        "ProducerRef",
        "REDUCED_STATE_FILE_NAME",
        "RawEventSeq",
        "RawPayloadId",
        "RawPayloadKind",
        "RawPayloadRef",
        "RawToolCallRequester",
        "RawTraceEvent",
        "RawTraceEventContext",
        "RawTraceEventPayload",
        "RolloutStatus",
        "RolloutTrace",
        "TerminalId",
        "TerminalModelObservation",
        "TerminalObservationSource",
        "TerminalOperation",
        "TerminalOperationId",
        "TerminalOperationKind",
        "TerminalRequest",
        "TerminalResult",
        "TerminalSession",
        "ThreadStartedTraceMetadata",
        "ThreadTraceContext",
        "TokenUsage",
        "ToolCall",
        "ToolCallId",
        "ToolCallKind",
        "ToolCallRequester",
        "ToolCallSummary",
        "ToolDispatchInvocation",
        "ToolDispatchPayload",
        "ToolDispatchRequester",
        "ToolDispatchResult",
        "ToolDispatchTraceContext",
        "TraceAnchor",
        "TraceWriter",
        "replay_bundle",
    }

    exported = set(rollout_trace.__all__)
    assert expected <= exported
    assert "_NormalizedConversationItem" not in exported
    assert "_apply_replayed_event" not in exported
    assert all(not name.startswith("_") for name in exported)

