"""Schema fixture helpers ported from ``schema_fixtures.rs``."""

from __future__ import annotations

import json
import shutil
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

JsonValue = Any
FixtureTree = dict[Path, bytes]

GENERATED_TS_HEADER = "// This file was generated by app-server-protocol.\n"


@dataclass(frozen=True)
class SchemaFixtureOptions:
    experimental_api: bool = False


def read_schema_fixture_tree(schema_root: str | Path) -> FixtureTree:
    root = Path(schema_root)
    all_files: FixtureTree = {}
    for rel, data in collect_files_recursive(root / "typescript").items():
        all_files[Path("typescript") / rel] = data
    for rel, data in collect_files_recursive(root / "json").items():
        all_files[Path("json") / rel] = data
    return dict(sorted(all_files.items(), key=lambda item: item[0].as_posix()))


def read_schema_fixture_subtree(schema_root: str | Path, label: str) -> FixtureTree:
    return collect_files_recursive(Path(schema_root) / label)


def write_schema_fixtures(
    schema_root: str | Path,
    prettier: str | Path | None = None,
    *,
    generate_ts: Callable[[Path, str | Path | None, SchemaFixtureOptions], None] | None = None,
    generate_json: Callable[[Path, bool], None] | None = None,
) -> None:
    write_schema_fixtures_with_options(
        schema_root,
        prettier,
        SchemaFixtureOptions(),
        generate_ts=generate_ts,
        generate_json=generate_json,
    )


def write_schema_fixtures_with_options(
    schema_root: str | Path,
    prettier: str | Path | None,
    options: SchemaFixtureOptions,
    *,
    generate_ts: Callable[[Path, str | Path | None, SchemaFixtureOptions], None] | None = None,
    generate_json: Callable[[Path, bool], None] | None = None,
) -> None:
    root = Path(schema_root)
    typescript_out_dir = root / "typescript"
    json_out_dir = root / "json"

    ensure_empty_dir(typescript_out_dir)
    ensure_empty_dir(json_out_dir)

    if generate_ts is None or generate_json is None:
        raise NotImplementedError("schema generation is owned by the export module")

    generate_ts(typescript_out_dir, prettier, options)
    generate_json(json_out_dir, options.experimental_api)


def generate_typescript_schema_fixture_subtree_for_tests() -> FixtureTree:
    raise NotImplementedError("TypeScript fixture generation is owned by the export module")


def ensure_empty_dir(path: str | Path) -> None:
    directory = Path(path)
    if directory.exists():
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)


def read_file_bytes(path: str | Path) -> bytes:
    file_path = Path(path)
    data = file_path.read_bytes()
    suffix = file_path.suffix.lower()
    if suffix == ".json":
        value = json.loads(data.decode("utf-8"))
        canonical = canonicalize_json(value)
        return json.dumps(canonical, indent=2, ensure_ascii=False).encode("utf-8")
    if suffix == ".ts":
        text = data.decode("utf-8")
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        if text.startswith(GENERATED_TS_HEADER):
            text = text[len(GENERATED_TS_HEADER) :]
        return text.encode("utf-8")
    return data


def canonicalize_json(value: JsonValue) -> JsonValue:
    if isinstance(value, list):
        items = [canonicalize_json(item) for item in value]
        sortable: list[tuple[str, str]] = []
        for item in items:
            key = schema_array_item_sort_key(item)
            if key is None:
                return items
            sortable.append((key, json.dumps(item, sort_keys=True, separators=(",", ":"))))
        paired = list(zip(items, sortable))
        paired.sort(key=lambda pair: (pair[1][0], pair[1][1]))
        return [item for item, _ in paired]
    if isinstance(value, dict):
        return OrderedDict((key, canonicalize_json(value[key])) for key in sorted(value))
    return value


def schema_array_item_sort_key(item: JsonValue) -> str | None:
    if item is None:
        return "null"
    if isinstance(item, bool):
        return f"b:{str(item).lower()}"
    if isinstance(item, (int, float)) and not isinstance(item, bool):
        return f"n:{item}"
    if isinstance(item, str):
        return f"s:{item}"
    if isinstance(item, dict):
        ref = item.get("$ref")
        if isinstance(ref, str):
            return f"ref:{ref}"
        title = item.get("title")
        if isinstance(title, str):
            return f"title:{title}"
        return None
    return None


def collect_files_recursive(root: str | Path) -> FixtureTree:
    root_path = Path(root)
    files: FixtureTree = {}
    if not root_path.exists():
        raise FileNotFoundError(str(root_path))
    stack = [root_path]
    while stack:
        directory = stack.pop()
        for entry in sorted(directory.iterdir(), key=lambda item: item.name):
            if entry.is_dir():
                stack.append(entry)
                continue
            if not entry.is_file():
                continue
            rel = entry.relative_to(root_path)
            files[rel] = read_file_bytes(entry)
    return dict(sorted(files.items(), key=lambda item: item[0].as_posix()))


def normalize_relative_fixture_path(path: str | Path) -> Path:
    return Path(*Path(path).parts)


def trim_trailing_line_whitespace(content: str | bytes) -> bytes:
    text = content.decode("utf-8") if isinstance(content, bytes) else content
    lines = [line.rstrip(" \t") for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    return "\n".join(lines).encode("utf-8")


__all__ = [
    "GENERATED_TS_HEADER",
    "FixtureTree",
    "SchemaFixtureOptions",
    "canonicalize_json",
    "collect_files_recursive",
    "ensure_empty_dir",
    "generate_typescript_schema_fixture_subtree_for_tests",
    "normalize_relative_fixture_path",
    "read_file_bytes",
    "read_schema_fixture_subtree",
    "read_schema_fixture_tree",
    "schema_array_item_sort_key",
    "trim_trailing_line_whitespace",
    "write_schema_fixtures",
    "write_schema_fixtures_with_options",
]
