"""Config lock helpers ported from ``core/src/config_lock.rs``.

The Rust implementation serializes comparison values through TOML. Python's
standard library can parse TOML but cannot emit it, so this module keeps the
same validation/comparison behavior and uses deterministic JSON text for the
compact diff.
"""

from __future__ import annotations

import copy
import difflib
import json
import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field, fields, is_dataclass
from datetime import date, datetime, time
from enum import Enum
from pathlib import Path
from typing import Any

from pycodex import __version__ as _PYCODEX_VERSION

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback surface.
    tomllib = None  # type: ignore[assignment]


CONFIG_LOCK_VERSION = 1
UPSTREAM_CONFIG_LOCK = "codex/codex-rs/core/src/config_lock.rs"


class ConfigLockError(OSError):
    """Raised when a config lock cannot be read, compared, or represented."""


@dataclass(frozen=True)
class ConfigLockReplayOptions:
    """Options used while replaying a generated config lock."""

    allow_codex_version_mismatch: bool = False


@dataclass(frozen=True)
class ConfigLockfile:
    """Python shape matching upstream ``ConfigLockfileToml``."""

    version: int
    codex_version: str
    config: dict[str, Any]
    upstream_source: str = field(default=UPSTREAM_CONFIG_LOCK, compare=False, repr=False)

    def __post_init__(self) -> None:
        if isinstance(self.version, bool) or not isinstance(self.version, int):
            raise config_lock_error("config lock version must be an integer")
        if not isinstance(self.codex_version, str):
            raise config_lock_error("config lock codex_version must be a string")
        object.__setattr__(self, "config", _copy_mapping(self.config, "config lock config"))


@dataclass(frozen=True)
class ConfigLockLayerEntry:
    """Small stand-in for upstream ``ConfigLayerEntry::new(User { .. }, value)``."""

    source_file: Path
    profile: str | None
    value: dict[str, Any]

    def __post_init__(self) -> None:
        object.__setattr__(self, "source_file", Path(self.source_file))
        object.__setattr__(self, "value", _copy_mapping(self.value, "config lock layer value"))


def config_lock_error(message: str) -> ConfigLockError:
    """Create an upstream-shaped config lock error."""

    return ConfigLockError(message)


def config_lockfile(
    config: Mapping[str, Any],
    codex_version: str = _PYCODEX_VERSION,
) -> ConfigLockfile:
    """Build a config lock around an effective config mapping."""

    return ConfigLockfile(
        version=CONFIG_LOCK_VERSION,
        codex_version=codex_version,
        config=_copy_mapping(config, "config lock config"),
    )


def read_config_lock_from_path(path: str | Path) -> ConfigLockfile:
    """Read, parse, and validate a config lock TOML file."""

    lock_path = Path(path)
    if tomllib is None:
        raise config_lock_error("tomllib is unavailable")

    try:
        with lock_path.open("rb") as file:
            data = tomllib.load(file)
    except OSError as exc:
        raise config_lock_error(f"failed to read config lock file {lock_path}: {exc}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise config_lock_error(f"failed to parse config lock file {lock_path}: {exc}") from exc

    try:
        lockfile = _lockfile_from_mapping(data, f"config lock file {lock_path}")
    except ConfigLockError as exc:
        raise config_lock_error(f"failed to parse config lock file {lock_path}: {exc}") from exc

    validate_config_lock_metadata_shape(lockfile)
    return lockfile


def validate_config_lock_replay(
    expected_lock: ConfigLockfile | Mapping[str, Any],
    actual_lock: ConfigLockfile | Mapping[str, Any],
    options: ConfigLockReplayOptions | None = None,
) -> None:
    """Validate that a replayed effective config matches the expected lock."""

    replay_options = options or ConfigLockReplayOptions()
    expected = _coerce_lockfile(expected_lock, "expected config lock")
    actual = _coerce_lockfile(actual_lock, "actual config lock")

    validate_config_lock_metadata_shape(expected)
    validate_config_lock_metadata_shape(actual)

    if not replay_options.allow_codex_version_mismatch and expected.codex_version != actual.codex_version:
        raise config_lock_error(
            "config lock Codex version mismatch: "
            f"lock was generated by {expected.codex_version}, current version is {actual.codex_version}; "
            "set debug.config_lockfile.allow_codex_version_mismatch=true to ignore this"
        )

    expected_for_comparison = config_lock_for_comparison(expected, replay_options)
    actual_for_comparison = config_lock_for_comparison(actual, replay_options)
    if expected_for_comparison != actual_for_comparison:
        try:
            diff = compact_diff("config", expected_for_comparison, actual_for_comparison)
        except ConfigLockError as exc:
            diff = f"failed to build config lock diff: {exc}"
        raise config_lock_error(f"replayed effective config does not match config lock: {diff}")


def lock_layer_from_config(
    lock_path: str | Path,
    lockfile: ConfigLockfile | Mapping[str, Any],
) -> ConfigLockLayerEntry:
    """Return the config layer value represented by a config lock."""

    lock = _coerce_lockfile(lockfile, "config lock")
    value = toml_value(config_without_lock_controls(lock.config), "config lock")
    return ConfigLockLayerEntry(source_file=Path(lock_path), profile=None, value=value)


def config_without_lock_controls(config: Mapping[str, Any]) -> dict[str, Any]:
    """Return a config copy with ``debug.config_lockfile`` controls removed."""

    config_copy = _copy_mapping(config, "config")
    clear_config_lock_debug_controls(config_copy)
    return config_copy


def clear_config_lock_debug_controls(config: dict[str, Any]) -> None:
    """Remove lock-control debug settings from a mutable config mapping."""

    debug = config.get("debug")
    if not isinstance(debug, dict):
        return

    debug.pop("config_lockfile", None)
    if not debug:
        config.pop("debug", None)


def validate_config_lock_metadata_shape(lockfile: ConfigLockfile | Mapping[str, Any]) -> None:
    """Validate metadata fields that are not part of the effective config."""

    lock = _coerce_lockfile(lockfile, "config lock")
    if lock.version != CONFIG_LOCK_VERSION:
        raise config_lock_error(
            f"unsupported config lock version {lock.version}; expected {CONFIG_LOCK_VERSION}"
        )


def config_lock_for_comparison(
    lockfile: ConfigLockfile | Mapping[str, Any],
    options: ConfigLockReplayOptions | None = None,
) -> ConfigLockfile:
    """Normalize a lock before comparing expected and replayed config values."""

    replay_options = options or ConfigLockReplayOptions()
    lock = _coerce_lockfile(lockfile, "config lock")
    codex_version = "" if replay_options.allow_codex_version_mismatch else lock.codex_version
    return ConfigLockfile(
        version=lock.version,
        codex_version=codex_version,
        config=config_without_lock_controls(lock.config),
    )


def compact_diff(root: str, expected: Any, actual: Any) -> str:
    """Build a compact unified diff for two TOML-compatible values."""

    try:
        expected_text = _stable_text(toml_value(expected, f"expected {root} lock TOML"))
    except ConfigLockError as exc:
        raise config_lock_error(f"failed to serialize expected {root} lock TOML: {exc}") from exc

    try:
        actual_text = _stable_text(toml_value(actual, f"actual {root} lock TOML"))
    except ConfigLockError as exc:
        raise config_lock_error(f"failed to serialize actual {root} lock TOML: {exc}") from exc

    return "".join(
        difflib.unified_diff(
            expected_text.splitlines(keepends=True),
            actual_text.splitlines(keepends=True),
            fromfile="expected",
            tofile="actual",
            n=2,
        )
    )


def toml_value(value: Any, label: str) -> Any:
    """Return a deep TOML-compatible representation of ``value``."""

    return _to_toml_shape(value, label)


def toml_round_trip(value: Any, label: str) -> Any:
    """Validate that ``value`` can round-trip through the supported TOML shape."""

    represented_value = toml_value(value, label)
    if toml_value(represented_value, label) != represented_value:
        raise config_lock_error(f"resolved {label} cannot be fully represented as TOML")
    return represented_value


def _coerce_lockfile(lockfile: ConfigLockfile | Mapping[str, Any], label: str) -> ConfigLockfile:
    if isinstance(lockfile, ConfigLockfile):
        return lockfile
    if isinstance(lockfile, Mapping):
        return _lockfile_from_mapping(lockfile, label)
    raise config_lock_error(f"{label} must be a config lock mapping")


def _lockfile_from_mapping(data: Mapping[str, Any], label: str) -> ConfigLockfile:
    version = data.get("version")
    codex_version = data.get("codex_version")
    config = data.get("config")
    if isinstance(version, bool) or not isinstance(version, int):
        raise config_lock_error(f"{label} is missing integer field 'version'")
    if not isinstance(codex_version, str):
        raise config_lock_error(f"{label} is missing string field 'codex_version'")
    if not isinstance(config, Mapping):
        raise config_lock_error(f"{label} is missing table field 'config'")
    return ConfigLockfile(version=version, codex_version=codex_version, config=_copy_mapping(config, label))


def _copy_mapping(value: Mapping[str, Any], label: str) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        raise config_lock_error(f"{label} must be a mapping")

    copied: dict[str, Any] = {}
    for key, item in value.items():
        if not isinstance(key, str):
            raise config_lock_error(f"{label} keys must be strings")
        copied[key] = copy.deepcopy(item)
    return copied


def _to_toml_shape(value: Any, label: str) -> Any:
    if isinstance(value, ConfigLockfile):
        return {
            "version": value.version,
            "codex_version": value.codex_version,
            "config": _to_toml_shape(value.config, label),
        }
    if isinstance(value, ConfigLockLayerEntry):
        return {
            "source_file": str(value.source_file),
            "profile": value.profile,
            "value": _to_toml_shape(value.value, label),
        }
    if is_dataclass(value):
        return {
            field_info.name: _to_toml_shape(getattr(value, field_info.name), label)
            for field_info in fields(value)
            if field_info.repr
        }
    if isinstance(value, Enum):
        return _to_toml_shape(value.value, label)
    if isinstance(value, Mapping):
        result: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise config_lock_error(f"{label} contains a non-string TOML key")
            result[key] = _to_toml_shape(item, label)
        return result
    if isinstance(value, (str, bool, int, date, datetime, time)):
        return copy.deepcopy(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise config_lock_error(f"{label} contains a non-finite float")
        return value
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return [_to_toml_shape(item, label) for item in value]
    if value is None:
        raise config_lock_error(f"{label} contains a null value, which TOML cannot represent")
    raise config_lock_error(f"{label} contains unsupported TOML value {type(value).__name__}")


def _stable_text(value: Any) -> str:
    return json.dumps(_json_projection(value), ensure_ascii=True, indent=2, sort_keys=True) + "\n"


def _json_projection(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _json_projection(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_projection(item) for item in value]
    if isinstance(value, (datetime, date, time)):
        return value.isoformat()
    return value


__all__ = [
    "CONFIG_LOCK_VERSION",
    "ConfigLockError",
    "ConfigLockLayerEntry",
    "ConfigLockReplayOptions",
    "ConfigLockfile",
    "clear_config_lock_debug_controls",
    "compact_diff",
    "config_lock_error",
    "config_lock_for_comparison",
    "config_lockfile",
    "config_without_lock_controls",
    "lock_layer_from_config",
    "read_config_lock_from_path",
    "toml_round_trip",
    "toml_value",
    "validate_config_lock_metadata_shape",
    "validate_config_lock_replay",
]
