"""Rust-aligned owner for ``codex-memories-write`` module items."""

from __future__ import annotations

from pathlib import Path
from pycodex.git_utils import GitBaselineDiff, GitToolingError, diff_since_latest_init
from pycodex.git_utils.baseline import BASELINE_COMMIT_MESSAGE
from pycodex.git_utils.operations import resolve_head, run_git_for_status
import os
import shutil
import stat

async def prepare_memory_workspace(root: str | Path) -> None:
    root_path = Path(root)
    root_path.mkdir(parents=True, exist_ok=True)
    await remove_workspace_diff(root_path)
    _ensure_memory_git_baseline(root_path)


async def memory_workspace_diff(root: str | Path) -> GitBaselineDiff:
    root_path = Path(root)
    await remove_workspace_diff(root_path)
    return diff_since_latest_init(root_path)


async def write_workspace_diff(root: str | Path, diff: GitBaselineDiff) -> None:
    path = Path(root) / PHASE2_WORKSPACE_DIFF_FILENAME
    path.write_text(render_workspace_diff_file(diff), encoding='utf-8')


async def reset_memory_workspace_baseline(root: str | Path) -> None:
    root_path = Path(root)
    await remove_workspace_diff(root_path)
    _reset_memory_git_baseline(root_path)


async def remove_workspace_diff(root: str | Path) -> None:
    path = Path(root) / PHASE2_WORKSPACE_DIFF_FILENAME
    try:
        path.unlink()
    except FileNotFoundError:
        return


def render_workspace_diff_file(diff: GitBaselineDiff) -> str:
    rendered = '# Memory Workspace Diff\n\nGenerated by Codex before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n## Status\n'
    if not diff.has_changes():
        return rendered + '- none\n'
    for change in diff.changes:
        rendered += f'- {change.status.label()} {change.path}\n'
    rendered += '\n## Diff\n\n```diff\n'
    rendered = _append_bounded_diff(rendered, diff.unified_diff)
    rendered += '```\n'
    return rendered


def previous_char_boundary(value: str, max_bytes: int) -> int:
    encoded = value.encode('utf-8')
    if max_bytes >= len(encoded):
        return len(encoded)
    index = max(0, int(max_bytes))
    while index > 0:
        try:
            encoded[:index].decode('utf-8')
            return index
        except UnicodeDecodeError:
            index -= 1
    return 0


def _ensure_memory_git_baseline(root: Path) -> None:
    if (root / '.git').is_dir():
        try:
            if (root / '.git' / 'HEAD').is_file() and resolve_head(root) is not None:
                run_git_for_status(root, ('read-tree', '--reset', 'HEAD'))
                return
        except GitToolingError:
            pass
    _reset_memory_git_baseline(root)


def _reset_memory_git_baseline(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    _remove_memory_git_metadata(root)
    run_git_for_status(root, ('init',))
    run_git_for_status(root, ('config', 'core.autocrlf', 'false'))
    run_git_for_status(root, ('add', '-A'))
    run_git_for_status(root, ('-c', 'user.name=Codex', '-c', 'user.email=noreply@openai.com', 'commit', '--allow-empty', '-m', BASELINE_COMMIT_MESSAGE), env=(('GIT_AUTHOR_NAME', 'Codex'), ('GIT_AUTHOR_EMAIL', 'noreply@openai.com'), ('GIT_COMMITTER_NAME', 'Codex'), ('GIT_COMMITTER_EMAIL', 'noreply@openai.com')))
    run_git_for_status(root, ('read-tree', '--reset', 'HEAD'))


def _remove_memory_git_metadata(root: Path) -> None:
    git_path = root / '.git'
    try:
        git_path.lstat()
    except FileNotFoundError:
        return
    if git_path.is_dir() and (not git_path.is_symlink()):
        shutil.rmtree(git_path, onerror=_make_writable_and_retry)
    else:
        git_path.unlink()


def _make_writable_and_retry(function, path: str, _exc_info) -> None:
    try:
        os.chmod(path, stat.S_IREAD | stat.S_IWRITE | stat.S_IEXEC)
    except OSError:
        pass
    function(path)


def _append_bounded_diff(rendered: str, diff: str) -> str:
    if len(diff.encode('utf-8')) <= PHASE2_WORKSPACE_DIFF_MAX_BYTES:
        rendered += diff
        if not diff.endswith('\n'):
            rendered += '\n'
        return rendered
    encoded = diff.encode('utf-8')
    boundary = previous_char_boundary(diff, PHASE2_WORKSPACE_DIFF_MAX_BYTES)
    rendered += encoded[:boundary].decode('utf-8')
    if not rendered.endswith('\n'):
        rendered += '\n'
    rendered += f'\n[workspace diff truncated at {PHASE2_WORKSPACE_DIFF_MAX_BYTES} bytes]\n'
    return rendered


from pycodex.memories.write.workspace_diff import FILENAME as PHASE2_WORKSPACE_DIFF_FILENAME
from pycodex.memories.write.workspace_diff import MAX_BYTES as PHASE2_WORKSPACE_DIFF_MAX_BYTES
