from __future__ import annotations


MAX_ADDITIONAL_CONTEXT_VALUE_TOKENS = 1_000
ADDITIONAL_CONTEXT_START_MARKER_PREFIX = "<external_"
ADDITIONAL_CONTEXT_END_MARKER_SUFFIX = ">"


__all__ = [
    "ADDITIONAL_CONTEXT_END_MARKER_SUFFIX",
    "ADDITIONAL_CONTEXT_START_MARKER_PREFIX",
    "MAX_ADDITIONAL_CONTEXT_VALUE_TOKENS",
]
