"""Public login module for the Python port.

The upstream project exposes login functionality under ``codex-rs/login``.
Legacy CLI-only helpers are exposed lazily so the Rust-aligned login package
does not acquire a reverse dependency on ``pycodex.cli`` during import.
"""

from __future__ import annotations

from importlib import import_module

from pycodex.login import auth
from pycodex.login.auth import default_client
from pycodex.login.auth_env_telemetry import (
    AuthEnvTelemetry,
    AuthEnvTelemetryMetadata,
    CODEX_API_KEY_ENV_VAR,
    OPENAI_API_KEY_ENV_VAR,
    REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR,
    collect_auth_env_telemetry,
    env_var_present,
)
from pycodex.login.auth.agent_identity import (
    AgentIdentityAuth,
    AgentIdentityAuthRecord,
    AgentIdentityKey,
    CODEX_AGENT_IDENTITY_AUTHAPI_BASE_URL_ENV_VAR,
    PROD_AGENT_IDENTITY_AUTHAPI_BASE_URL,
    agent_identity_authapi_base_url,
)
from pycodex.login.auth.error import RefreshTokenFailedError, RefreshTokenFailedReason
from pycodex.login.auth.external_bearer import (
    BearerTokenRefresher,
    ExternalAuthRefreshContext,
    ExternalAuthTokens,
    resolve_provider_auth_program,
    run_provider_auth_command,
)
from pycodex.login.auth.manager import (
    CLIENT_ID,
    CODEX_ACCESS_TOKEN_ENV_VAR,
    DEFAULT_CHATGPT_BACKEND_BASE_URL,
    EXTERNAL_AUTH_MODE_API_KEY,
    ApiKeyAuth,
    AuthConfig,
    AuthManager,
    AuthManagerConfig,
    ChatgptAuth,
    ChatgptAuthTokens,
    CodexAuth,
    ExternalAuth,
    ExternalAuthChatgptMetadata,
    ExternalAuthRefreshReason,
    ManagerExternalAuthTokens,
    RefreshTokenError,
    UnauthorizedRecovery,
    UnauthorizedRecoveryStepResult,
    auth_dot_json_from_external_access_token,
    auth_dot_json_from_external_tokens,
    classify_refresh_token_failure,
    enforce_login_restrictions,
    extract_refresh_token_error_code,
    load_auth,
    load_auth_dot_json,
    login_with_access_token,
    login_with_api_key,
    login_with_chatgpt_auth_tokens,
    logout,
    logout_all_stores,
    logout_with_revoke,
    persist_tokens,
    read_codex_access_token_from_env,
    read_codex_api_key_from_env,
    read_openai_api_key_from_env,
    refresh_token_endpoint,
    resolved_mode,
    save_auth,
    storage_mode,
)
from pycodex.login.auth.revoke import revoke_auth_tokens, should_revoke_auth_tokens
from pycodex.login.auth.storage import (
    AuthDotJson as StorageAuthDotJson,
    create_auth_storage,
    delete_file_if_exists,
    get_auth_file,
)
from pycodex.login.auth.util import try_parse_error_message
from pycodex.login.device_code_auth import (
    DeviceCode,
    complete_device_code_login,
    request_device_code,
    run_device_code_login,
)
from pycodex.login.server import LoginServer, ServerOptions, ShutdownHandle, run_login_server
from pycodex.login.token_data import TokenData

__all__ = [
    "AUTH_FILE",
    "AUTH_MODE_API_KEY",
    "AUTH_MODE_CHATGPT",
    "AUTH_MODE_CHATGPT_AUTH_TOKENS",
    "AUTH_MODE_AGENT_IDENTITY",
    "AuthDotJson",
    "auth_file_path",
    "delete_auth_file",
    "default_client",
    "read_auth_json",
    "resolve_auth_mode",
    "run_chatgpt_login",
    "safe_format_key",
    "write_auth_json",
    "auth",
    "BuildLoginHttpClientError",
    "CLIENT_ID",
    "AuthEnvTelemetry",
    "AuthEnvTelemetryMetadata",
    "ApiKeyAuth",
    "AuthConfig",
    "AuthManager",
    "AuthManagerConfig",
    "ChatgptAuth",
    "ChatgptAuthTokens",
    "CodexAuth",
    "ExternalAuth",
    "ExternalAuthChatgptMetadata",
    "ExternalAuthRefreshReason",
    "ManagerExternalAuthTokens",
    "RefreshTokenError",
    "UnauthorizedRecovery",
    "UnauthorizedRecoveryStepResult",
    "StorageAuthDotJson",
    "CODEX_ACCESS_TOKEN_ENV_VAR",
    "CODEX_API_KEY_ENV_VAR",
    "DEFAULT_CHATGPT_BACKEND_BASE_URL",
    "EXTERNAL_AUTH_MODE_API_KEY",
    "OPENAI_API_KEY_ENV_VAR",
    "REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR",
    "REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR",
    "collect_auth_env_telemetry",
    "env_var_present",
    "RefreshTokenFailedError",
    "RefreshTokenFailedReason",
    "AgentIdentityAuth",
    "AgentIdentityAuthRecord",
    "AgentIdentityKey",
    "CODEX_AGENT_IDENTITY_AUTHAPI_BASE_URL_ENV_VAR",
    "PROD_AGENT_IDENTITY_AUTHAPI_BASE_URL",
    "agent_identity_authapi_base_url",
    "BearerTokenRefresher",
    "ExternalAuthRefreshContext",
    "ExternalAuthTokens",
    "DeviceCode",
    "LoginServer",
    "ServerOptions",
    "ShutdownHandle",
    "TokenData",
    "auth_dot_json_from_external_access_token",
    "auth_dot_json_from_external_tokens",
    "classify_refresh_token_failure",
    "complete_device_code_login",
    "create_auth_storage",
    "delete_file_if_exists",
    "enforce_login_restrictions",
    "extract_refresh_token_error_code",
    "get_auth_file",
    "load_auth",
    "load_auth_dot_json",
    "login_with_access_token",
    "login_with_api_key",
    "login_with_chatgpt_auth_tokens",
    "logout",
    "logout_all_stores",
    "logout_with_revoke",
    "persist_tokens",
    "request_device_code",
    "read_codex_access_token_from_env",
    "read_codex_api_key_from_env",
    "read_openai_api_key_from_env",
    "refresh_token_endpoint",
    "resolve_provider_auth_program",
    "resolved_mode",
    "revoke_auth_tokens",
    "run_provider_auth_command",
    "run_device_code_login",
    "run_login_server",
    "save_auth",
    "should_revoke_auth_tokens",
    "storage_mode",
    "try_parse_error_message",
]

BuildLoginHttpClientError = OSError
REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR = "CODEX_REVOKE_TOKEN_URL_OVERRIDE"


def __getattr__(name: str):
    if name in {
        "AuthEnvTelemetry",
        "AuthEnvTelemetryMetadata",
        "CLIENT_ID",
        "ApiKeyAuth",
        "AuthConfig",
        "AuthManager",
        "AuthManagerConfig",
        "ChatgptAuth",
        "ChatgptAuthTokens",
        "CodexAuth",
        "ExternalAuth",
        "ExternalAuthChatgptMetadata",
        "ExternalAuthRefreshReason",
        "ManagerExternalAuthTokens",
        "RefreshTokenError",
        "UnauthorizedRecovery",
        "UnauthorizedRecoveryStepResult",
        "CODEX_ACCESS_TOKEN_ENV_VAR",
        "CODEX_API_KEY_ENV_VAR",
        "DEFAULT_CHATGPT_BACKEND_BASE_URL",
        "EXTERNAL_AUTH_MODE_API_KEY",
        "OPENAI_API_KEY_ENV_VAR",
        "REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR",
        "collect_auth_env_telemetry",
        "env_var_present",
        "RefreshTokenFailedError",
        "RefreshTokenFailedReason",
        "AgentIdentityAuth",
        "AgentIdentityAuthRecord",
        "AgentIdentityKey",
        "CODEX_AGENT_IDENTITY_AUTHAPI_BASE_URL_ENV_VAR",
        "PROD_AGENT_IDENTITY_AUTHAPI_BASE_URL",
        "agent_identity_authapi_base_url",
        "BearerTokenRefresher",
        "ExternalAuthRefreshContext",
        "ExternalAuthTokens",
        "resolve_provider_auth_program",
        "run_provider_auth_command",
        "DeviceCode",
        "LoginServer",
        "ServerOptions",
        "ShutdownHandle",
        "TokenData",
        "auth_dot_json_from_external_access_token",
        "auth_dot_json_from_external_tokens",
        "classify_refresh_token_failure",
        "complete_device_code_login",
        "create_auth_storage",
        "delete_file_if_exists",
        "enforce_login_restrictions",
        "extract_refresh_token_error_code",
        "get_auth_file",
        "load_auth",
        "load_auth_dot_json",
        "login_with_access_token",
        "login_with_api_key",
        "login_with_chatgpt_auth_tokens",
        "logout",
        "logout_all_stores",
        "logout_with_revoke",
        "persist_tokens",
        "request_device_code",
        "read_codex_access_token_from_env",
        "read_codex_api_key_from_env",
        "read_openai_api_key_from_env",
        "refresh_token_endpoint",
        "revoke_auth_tokens",
        "run_device_code_login",
        "run_login_server",
        "save_auth",
        "should_revoke_auth_tokens",
        "storage_mode",
        "resolved_mode",
        "try_parse_error_message",
        "auth",
        "default_client",
        "BuildLoginHttpClientError",
        "REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR",
        "StorageAuthDotJson",
    }:
        return globals()[name]
    if name not in __all__:
        raise AttributeError(name)
    return getattr(import_module("pycodex.cli.login"), name)


def __dir__() -> list[str]:
    return sorted(__all__)
