"""Core plugin modules aligned with ``codex-rs/core/src/plugins``."""

from .mentions import (
    APP_PATH_PREFIX,
    MCP_PATH_PREFIX,
    PLUGIN_PATH_PREFIX,
    SKILL_FILENAME,
    SKILL_PATH_PREFIX,
    CollectedToolMentions,
    ToolMentionKind,
    ToolMentions,
    app_id_from_path,
    build_connector_slug_counts,
    collect_explicit_app_ids,
    collect_explicit_plugin_mentions,
    collect_tool_mentions_from_messages,
    collect_tool_mentions_from_messages_with_sigil,
    extract_tool_mentions,
    extract_tool_mentions_with_sigil,
    is_skill_filename,
    normalize_skill_path,
    plugin_config_name_from_path,
    tool_kind_for_path,
)

__all__ = [
    "APP_PATH_PREFIX",
    "MCP_PATH_PREFIX",
    "PLUGIN_PATH_PREFIX",
    "SKILL_FILENAME",
    "SKILL_PATH_PREFIX",
    "CollectedToolMentions",
    "ToolMentionKind",
    "ToolMentions",
    "app_id_from_path",
    "build_connector_slug_counts",
    "collect_explicit_app_ids",
    "collect_explicit_plugin_mentions",
    "collect_tool_mentions_from_messages",
    "collect_tool_mentions_from_messages_with_sigil",
    "extract_tool_mentions",
    "extract_tool_mentions_with_sigil",
    "is_skill_filename",
    "normalize_skill_path",
    "plugin_config_name_from_path",
    "tool_kind_for_path",
]
