"""Runtime helpers mirroring ``codex-experimental-api-macros``.

Rust implements this crate as a proc-macro derive. Python cannot expand Rust
tokens, so this module exposes the same generated behavior as decorators and
field metadata for protocol shims and tests.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import Field, dataclass, fields, is_dataclass
from enum import Enum
from typing import Any, Callable, Literal, TypeVar, overload

from pycodex.app_server_protocol.experimental_api import (
    ExperimentalField,
    experimental_reason,
    register_experimental_field,
)

PresenceKind = Literal["option", "collection", "map", "bool", "always"]

_EXPERIMENTAL_REASON = "experimental_reason"
_EXPERIMENTAL_NESTED = "experimental_nested"
_EXPERIMENTAL_PRESENCE = "experimental_presence"

T = TypeVar("T", bound=type)


@dataclass(frozen=True)
class ExperimentalRule:
    field_name: str
    reason: str
    presence: PresenceKind = "always"
    access_name: str | int | None = None


@dataclass(frozen=True)
class NestedRule:
    access_name: str | int


def experimental_metadata(reason: str, *, presence: PresenceKind = "always") -> dict[str, str]:
    return {
        _EXPERIMENTAL_REASON: reason,
        _EXPERIMENTAL_PRESENCE: presence,
    }


def nested_metadata() -> dict[str, bool]:
    return {_EXPERIMENTAL_NESTED: True}


@overload
def derive_experimental_api(cls: T, /) -> T:
    ...


@overload
def derive_experimental_api(
    *,
    enum_reasons: Mapping[str, str] | None = None,
    fields: Sequence[ExperimentalRule] = (),
    nested: Sequence[NestedRule] = (),
) -> Callable[[T], T]:
    ...


def derive_experimental_api(
    cls: T | None = None,
    /,
    *,
    enum_reasons: Mapping[str, str] | None = None,
    fields: Sequence[ExperimentalRule] = (),
    nested: Sequence[NestedRule] = (),
) -> T | Callable[[T], T]:
    """Attach the behavior generated by Rust ``#[derive(ExperimentalApi)]``."""

    def decorate(target: T) -> T:
        if issubclass(target, Enum):
            return _derive_enum(target, enum_reasons or {})
        return _derive_struct(target, fields, nested)

    if cls is not None:
        return decorate(cls)
    return decorate


def snake_to_camel(value: str) -> str:
    out: list[str] = []
    upper = False
    for char in value:
        if char == "_":
            upper = True
            continue
        if upper:
            out.append(char.upper())
            upper = False
        else:
            out.append(char)
    return "".join(out)


def presence_for_value(value: Any, presence: PresenceKind) -> bool:
    if presence == "option":
        return value is not None
    if presence in {"collection", "map"}:
        return len(value) > 0
    if presence == "bool":
        return bool(value)
    return True


def experimental_reason_for_struct(
    value: Any,
    field_rules: Sequence[ExperimentalRule],
    nested_rules: Sequence[NestedRule] = (),
) -> str | None:
    for rule in field_rules:
        field_value = _access(value, rule.access_name if rule.access_name is not None else rule.field_name)
        if presence_for_value(field_value, rule.presence):
            return rule.reason
    for rule in nested_rules:
        reason = experimental_reason(_access(value, rule.access_name))
        if reason is not None:
            return reason
    return None


def _derive_enum(target: T, enum_reasons: Mapping[str, str]) -> T:
    def experimental_reason_method(self: Enum) -> str | None:
        return enum_reasons.get(self.name)

    setattr(target, "experimental_reason", experimental_reason_method)
    return target


def _derive_struct(
    target: T,
    explicit_fields: Sequence[ExperimentalRule],
    explicit_nested: Sequence[NestedRule],
) -> T:
    field_rules = list(explicit_fields)
    nested_rules = list(explicit_nested)
    ordered_checks: list[tuple[str, ExperimentalRule | NestedRule]] = [
        *[("field", rule) for rule in field_rules],
        *[("nested", rule) for rule in nested_rules],
    ]
    if is_dataclass(target):
        for field in fields(target):
            rule = _rule_from_dataclass_field(field)
            if rule is not None:
                field_rules.append(rule)
                ordered_checks.append(("field", rule))
            if field.metadata.get(_EXPERIMENTAL_NESTED) is True:
                nested_rule = NestedRule(field.name)
                nested_rules.append(nested_rule)
                ordered_checks.append(("nested", nested_rule))

    type_name = target.__name__
    experimental_fields = tuple(
        ExperimentalField(type_name=type_name, field_name=rule.field_name, reason=rule.reason)
        for rule in field_rules
    )
    setattr(target, "EXPERIMENTAL_FIELDS", experimental_fields)
    for item in experimental_fields:
        register_experimental_field(item.type_name, item.field_name, item.reason)

    def experimental_reason_method(self: Any) -> str | None:
        for kind, rule in ordered_checks:
            if kind == "field":
                assert isinstance(rule, ExperimentalRule)
                field_value = _access(
                    self,
                    rule.access_name if rule.access_name is not None else rule.field_name,
                )
                if presence_for_value(field_value, rule.presence):
                    return rule.reason
            else:
                assert isinstance(rule, NestedRule)
                reason = experimental_reason(_access(self, rule.access_name))
                if reason is not None:
                    return reason
        return None

    setattr(target, "experimental_reason", experimental_reason_method)
    return target


def _rule_from_dataclass_field(field: Field[Any]) -> ExperimentalRule | None:
    reason = field.metadata.get(_EXPERIMENTAL_REASON)
    if not isinstance(reason, str):
        return None
    presence = field.metadata.get(_EXPERIMENTAL_PRESENCE, "always")
    if presence not in {"option", "collection", "map", "bool", "always"}:
        raise ValueError(f"unsupported experimental presence kind: {presence}")
    return ExperimentalRule(
        field_name=snake_to_camel(field.name),
        reason=reason,
        presence=presence,
        access_name=field.name,
    )


def _access(value: Any, name: str | int) -> Any:
    if isinstance(name, int):
        return value[name]
    if isinstance(value, Mapping):
        return value[name]
    return getattr(value, name)


__all__ = [
    "ExperimentalRule",
    "NestedRule",
    "derive_experimental_api",
    "experimental_metadata",
    "experimental_reason_for_struct",
    "nested_metadata",
    "presence_for_value",
    "snake_to_camel",
]
